### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by sp7412** [AVAuco/deeparuco#1]
Can you provide details about how many samples the datasets have? Will the datasets be available for use?

**Comment by rafabs97** [comment]
Dataset composition and creation will be detailed on a future publication (currently pending approval).

**Comment by rafabs97** [comment]
Hey there! We recently published our dataset along with the data generation scripts. Feel free to check it out! Closing this for now, feel free to open a new issue if you have any other questions 🙂
